param(
    [string]$DateFrom = "",
    [string]$DateTo = "",
    [string]$Material = "",
    [string]$Plant = "P001",
    [string]$StorageLoc = "",
    [string]$MovementType = "",
    [string]$ApiBaseUrl = "http://localhost:3000",
    [switch]$SkipUpload
)

$ErrorActionPreference = "Continue"
$Desktop = [Environment]::GetFolderPath("Desktop")
$DownloadDir = Join-Path $Desktop "SAP_MB51"
if (-not (Test-Path $DownloadDir)) { New-Item -ItemType Directory -Path $DownloadDir -Force | Out-Null }

$LogFile = Join-Path $DownloadDir "mb51_ps_log.txt"
function Write-Log {
    param([string]$Message)
    $timestamp = Get-Date -Format "HH:mm:ss"
    $line = "[$timestamp] $Message"
    Write-Output $line
    Add-Content -Path $LogFile -Value $line
}

Write-Log "=== MB51 AUTO IMPORTER ==="
Write-Log "DateFrom=$DateFrom DateTo=$DateTo Plant=$Plant"

# ─── Cari VBS ───
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$VbsPath = Join-Path $ScriptDir "mb51-export.vbs"

# Fallback paths
$altPaths = @(
    $VbsPath,
    Join-Path $ScriptDir "..\scripts\mb51-export.vbs",
    "C:\spindo\NextJS\IN-OUT Gudang\daily-report\scripts\mb51-export.vbs"
)

$foundVbs = $null
foreach ($p in $altPaths) {
    $resolved = Resolve-Path $p -ErrorAction SilentlyContinue
    if ($resolved) { $foundVbs = $resolved.Path; break }
}

if (-not $foundVbs) {
    Write-Log "ERROR: mb51-export.vbs not found"
    Write-Output "ERROR_VBS_NOT_FOUND=Cannot find mb51-export.vbs in project scripts folder"
    exit 1
}

Write-Log "VBS: $foundVbs"

# ─── Generate parameterized VBS temp file ───
$tempVbs = Join-Path $env:TEMP "mb51_run_$(Get-Date -Format 'yyyyMMdd_HHmmss').vbs"
$vbsContent = @"
' Auto-generated by PowerShell Auto Importer
TransactionCode = "MB51"
DateFrom = "$DateFrom"
DateTo = "$DateTo"
Material = "$Material"
Plant = "$Plant"
StorageLoc = "$StorageLoc"
MovementType = "$MovementType"
"@

# Read original VBS but replace the CONFIG section
$origContent = Get-Content $foundVbs -Raw
$configMarker = "' ════════════════════════════════════════════"
$configEndMarker = "' ════════════════════════════════════════════"
$lines = $origContent -split "`r`n|`n"

# Find the config block and insert our parameters
$inConfig = $false
$inHeader = $false
$newLines = @()
foreach ($line in $lines) {
    if ($line -match "' ═+") { 
        if (-not $inHeader) { $inHeader = $true }
        elseif (-not $inConfig) { $inConfig = $true; $newLines += $line; $newLines += $vbsContent; continue }
        elseif ($inConfig) { $inConfig = $false }
    }
    if (-not $inConfig) { $newLines += $line }
}
$newContent = $newLines -join "`r`n"
Set-Content -Path $tempVbs -Value $newContent -Encoding UTF8
Write-Log "Temp VBS: $tempVbs"

# ─── Hitung file existing ───
$existingFiles = @(Get-ChildItem -Path $DownloadDir -Filter "MB51_Export_*.xlsx" -ErrorAction SilentlyContinue)
$existingCount = $existingFiles.Count
$beforeFiles = @(Get-ChildItem -Path $DownloadDir -Filter "*.xlsx" -ErrorAction SilentlyContinue | Select-Object -ExpandProperty FullName)

# ─── Jalankan VBS via cscript 32-bit ───
Write-Log "Running MB51 export ..."
$cscript = "C:\Windows\SysWOW64\cscript.exe"

# Run cscript with 60s timeout
$psi = New-Object System.Diagnostics.ProcessStartInfo
$psi.FileName = $cscript
$psi.Arguments = "//NoLogo `"$tempVbs`""
$psi.UseShellExecute = $false
$psi.RedirectStandardOutput = $true
$psi.RedirectStandardError = $true
$psi.CreateNoWindow = $true

$proc = New-Object System.Diagnostics.Process
$proc.StartInfo = $psi

$output = [System.Text.StringBuilder]::new()
$errorOut = [System.Text.StringBuilder]::new()

$outEvent = Register-ObjectEvent -InputObject $proc -EventName OutputDataReceived -Action { $output.AppendLine($Event.SourceEventArgs.Data) }
$errEvent = Register-ObjectEvent -InputObject $proc -EventName ErrorDataReceived -Action { $errorOut.AppendLine($Event.SourceEventArgs.Data) }

$proc.Start() | Out-Null
$proc.BeginOutputReadLine()
$proc.BeginErrorReadLine()

# Wait max 120s
$completed = $proc.WaitForExit(120000)
if (-not $completed) {
    Write-Log "TIMEOUT: VBS script did not finish in 120s — check SAP GUI for popups/dialogs"
    $proc.Kill()
    Write-Output "ERROR_TIMEOUT=VBS script timed out. Mungkin ada popup SAP yang perlu ditutup manual."
    
    # Cari file baru yang mungkin sudah terlanjur ke-export
    $afterFiles = @(Get-ChildItem -Path $DownloadDir -Filter "*.xlsx" -ErrorAction SilentlyContinue | Select-Object -ExpandProperty FullName)
    $newFiles = $afterFiles | Where-Object { $_ -notin $beforeFiles }
    if ($newFiles.Count -gt 0) {
        $exportFile = $newFiles[-1]
        Write-Log "TIMEOUT but file found: $exportFile"
        Write-Output "TIMEOUT_WITH_FILE=$exportFile"
    }
    
    Unregister-Event -SourceIdentifier $outEvent.Id -ErrorAction SilentlyContinue
    Unregister-Event -SourceIdentifier $errEvent.Id -ErrorAction SilentlyContinue
    exit 1
}

$proc.Close()

$allOutput = $output.ToString().Trim()
$allError = $errorOut.ToString().Trim()

Unregister-Event -SourceIdentifier $outEvent.Id -ErrorAction SilentlyContinue
Unregister-Event -SourceIdentifier $errEvent.Id -ErrorAction SilentlyContinue

Write-Log "VBS exit code: $($proc.ExitCode)"
if ($allOutput) { Write-Log "Output: $($allOutput -replace "`n",' | ')" }
if ($allError) { Write-Log "Stderr: $allError" }

# ─── Bersihkan temp ───
Remove-Item $tempVbs -Force -ErrorAction SilentlyContinue

# ─── Parse output untuk RESULTFILE ───
$resultFile = $null
foreach ($line in $allOutput -split "`n") {
    $line = $line.Trim()
    if ($line -match "^RESULTFILE=(.+)") { $resultFile = $matches[1] }
    if ($line -match "^PENDINGMANUAL=(.+)") { Write-Output "MANUAL_NEEDED=$($matches[1])" }
}

if (-not $resultFile) {
    # Cari file baru di download dir
    $afterFiles = @(Get-ChildItem -Path $DownloadDir -Filter "*.xlsx" -ErrorAction SilentlyContinue | Select-Object -ExpandProperty FullName)
    $newFiles = $afterFiles | Where-Object { $_ -notin $beforeFiles }
    if ($newFiles.Count -gt 0) {
        $resultFile = $newFiles[-1]
        Write-Log "Found file via scan: $resultFile"
    }
}

if ($resultFile -and (Test-Path $resultFile)) {
    Write-Log "EXPORTED: $resultFile"
    Write-Output "EXPORTED_FILE=$resultFile"

    if (-not $SkipUpload) {
        Write-Log "Uploading to $ApiBaseUrl/api/sap/mb51-auto-import ..."
        try {
            # Upload via multipart form
            $uploadResult = Invoke-WebRequest -Uri "$ApiBaseUrl/api/sap/mb51-auto-import" `
                -Method POST `
                -Form @{
                    file = Get-Item -Path $resultFile
                    label = "MB51 $DateFrom - $DateTo"
                } `
                -UseBasicParsing `
                -ErrorAction SilentlyContinue

            Write-Log "Upload HTTP: $($uploadResult.StatusCode)"
            $response = $uploadResult.Content | ConvertFrom-Json

            if ($uploadResult.StatusCode -eq 200) {
                Write-Output "UPLOAD_SUCCESS=Session $($response.reportSessionId) — $($response.movementCount) movements imported"
            } else {
                Write-Output "UPLOAD_FAILED=$($response.error)"
            }
        } catch {
            Write-Log "ERROR uploading: $_"
            Write-Output "UPLOAD_FAILED=$_"
            Write-Output "MANUAL_UPLOAD=Upload file berikut ke Web App: $resultFile"
        }
    }
} else {
    Write-Log "No export file found"
    Write-Output "NO_FILE=Export file tidak ditemukan. Coba jalankan SAP GUI script manual."
}

Write-Log "=== MB51 AUTO IMPORTER END ==="
